INSERT INTO public.rooms
(id, room_name_sr, room_name_en, room_name_bg, room_short_des_sr, room_short_des_en, room_short_des_bg, room_description_sr, room_description_en, room_description_bg, room_pictures_folder,room_guest_number, room_price_en, created_at, updated_at)
VALUES(1, 'Soba 1 sa Bračnim Krevetom (King-size)','Room 1 with Double Bed (King-size)','Стая 1 с двойно легло (king-size)', '1 veliki bračni krevet','1 large double bed','1 голямо двойно легло','Ova dvokrevetna soba sa besplatnim toaletnim priborom ima sopstveno kupatilo sa kadom i tušem. Ova dvokrevetna soba ima klima-uređaj i TV ravnog ekrana. Jedinica ima 1 krevet.','Featuring free toiletries, this double room includes a private bathroom with a bath and a shower. This double room features air conditioning and a flat-screen TV. The unit has 1 bed.','Тази двойна стая включва безплатни тоалетни принадлежности и самостоятелна баня с вана и душ. Тази двойна стая разполага с климатик и телевизор с плосък екран. Помещението разполага с 1 легло.','prva',2,44,'2023-11-17 00:00:00.000', '2023-11-17 00:00:00.000');
INSERT INTO public.rooms
(id, room_name_sr, room_name_en, room_name_bg, room_short_des_sr, room_short_des_en, room_short_des_bg, room_description_sr, room_description_en, room_description_bg, room_pictures_folder,room_guest_number, room_price_en, created_at, updated_at)
VALUES(2, 'Soba 2 sa Bračnim Krevetom (King-size)','Room 2 with Double Bed (King-size)','Стая 2 с двойно легло (king-size)', '1 veliki bračni krevet','1 large double bed','1 голямо двойно легло','Ova dvokrevetna soba sa besplatnim toaletnim priborom ima sopstveno kupatilo sa kadom i tušem. Ova dvokrevetna soba ima klima-uređaj i TV ravnog ekrana. Jedinica ima 1 krevet.','Featuring free toiletries, this double room includes a private bathroom with a bath and a shower. This double room features air conditioning and a flat-screen TV. The unit has 1 bed.','Тази двойна стая включва безплатни тоалетни принадлежности и самостоятелна баня с вана и душ. Тази двойна стая разполага с климатик и телевизор с плосък екран. Помещението разполага с 1 легло.','druga',2,44,'2023-11-17 00:00:00.000', '2023-11-17 00:00:00.000');
INSERT INTO public.rooms
(id, room_name_sr, room_name_en, room_name_bg, room_short_des_sr, room_short_des_en, room_short_des_bg, room_description_sr, room_description_en, room_description_bg, room_pictures_folder,room_guest_number, room_price_en, created_at, updated_at)
VALUES(3, 'Dvokrevetna Soba sa Zasebnim Krevetima','Double Room with Separate Beds','Двойна стая с отделни легла', '2 kreveta za 1 osobu','2 beds for 1 person','2 легла за 1 човек','Ova dvokrevetna soba sa besplatnim toaletnim priborom ima sopstveno kupatilo sa kadom i tušem. Ova dvokrevetna soba ima klima-uređaj i TV ravnog ekrana. Jedinica ima 1 krevet.','Offering free toiletries, this twin room includes a private bathroom with a bath and a shower. This twin room offers air conditioning and a flat-screen TV. The unit has 2 beds.','Тази стая с 2 отделни легла предлага безплатни тоалетни принадлежности и самостоятелна баня с вана и душ. Тази стая с 2 отделни легла предлага климатик и телевизор с плосък екран. Помещението е с 2 легла.','treca',2,49,'2023-11-17 00:00:00.000', '2023-11-17 00:00:00.000');
INSERT INTO public.rooms
(id, room_name_sr, room_name_en, room_name_bg, room_short_des_sr, room_short_des_en, room_short_des_bg, room_description_sr, room_description_en, room_description_bg, room_pictures_folder,room_guest_number, room_price_en, created_at, updated_at)
VALUES(4, 'Trokrevetna Soba','Three bed room','Стая с три спални', '3 kreveta za 1 osobu','3 beds for 1 person','3 легла за 1 човек','Ova trokrevetna soba nudi besplatne toaletne potrepštine i sopstveno kupatilo sa kadom i tušem. Ova trokrevetna soba ima klima-uređaj i TV ravnog ekrana. Jedinica ima 3 kreveta.','Offering free toiletries, this triple room includes a private bathroom with a bath and a shower. This triple room offers air conditioning and a flat-screen TV. The unit has 3 beds.','Тази тройна стая предлага безплатни тоалетни принадлежности и самостоятелна баня с вана и душ. Тази тройна стая разполага с климатик и телевизор с плосък екран. Блокът е с 3 легла.','cetvrta',3,53,'2023-11-17 00:00:00.000', '2023-11-17 00:00:00.000');
INSERT INTO public.rooms
(id, room_name_sr, room_name_en, room_name_bg, room_short_des_sr, room_short_des_en, room_short_des_bg, room_description_sr, room_description_en, room_description_bg, room_pictures_folder,room_guest_number, room_price_en, created_at, updated_at)
VALUES(5, 'Četvorokrevetna Soba','Four-bed room','Стая с четири легла', '1 krevet za 1 osobu i 1 kauč na razvlačenje i 1 veliki bračni krevet','1 single bed and 1 sofa bed and 1 large double bed','1 единично легло и 1 разтегателен диван и 1 голямо двойно легло','Ova četvorokrevetna soba sa besplatnim toaletnim priborom ima sopstveno kupatilo sa kadom i tušem. Ova četvorokrevetna soba ima klima-uređaj, sofu i TV ravnog ekrana. Jedinica ima 3 ležaja.','Providing free toiletries, this quadruple room includes a private bathroom with a bath and a shower. This quadruple room features air conditioning, a sofa and a flat-screen TV. The unit offers 3 beds.','Тази четворна стая включва безплатни тоалетни принадлежности и самостоятелна баня с вана и душ. Тази четворна стая разполага с климатик, диван и телевизор с плосък екран. Помещението разполага с 3 легла.','peta',4,57,'2023-11-17 00:00:00.000', '2023-11-17 00:00:00.000');